### ISSUE TITLE
Please add ngx-masonry to package.json

### ISSUE THREAD

**Issue by tim1016** [wynfred/ngx-masonry-demo#1]
I read some where ngx-masonry is now a peer dependency. Does that mean you have to add it into package.json. I got import error, and then installed it. then demo worked fine.

**Comment by tim1016** [comment]
I see that the demo does not produce a smooth edge for the gallery at the bottom. Is is due to the option that user can load more images, so jagged bottom  is fine. For a fixed set of images, are there options in this package to have a smooth edge?

**Comment by wynfred** [comment]
- The demo doesn't have ngx-masonry because it has a link to the project - https://github.com/wynfred/ngx-masonry-demo/tree/master/projects , you need to pull the project and build it locally. What you did works if you don't want to debug/modify the library.
- There is no guarantee of the height of each column because it's just a sum of the height of images.
- Issues in this repo are not monitored. Please open issue in the library repo so you can get response sooner.
